# Generated by Django 5.1.3 on 2025-03-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
